name: '${project.artifactId}'
version: '${project.version}'
main: '${project.groupId}.${project.artifactId}'
api-version: 1.19
authors: [KIZAFOX]
description: '${project.description}'
website: '${project.url}'